# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is an application:  ../bin/qunotefort

FORMS += MainWin.ui \
         TitleWin.ui 
HEADERS += main.h \
           ListBoxItem.h \
           Thread.h 
SOURCES += qunotefort.cpp \
           main.cpp \
           ListBoxItem.cpp 
TARGET=../bin/qunotefort
